

{
    "name": "Project Scrum Core",
    "summary": "Depend Modules For Project for first install after db installation",
    "version": "14.0.1.0.0",
    "author": "Ahmed Abdu",
    "website": "ahmedabdu.odoo@gmail.com",
    "license": "LGPL-3",
    "installable": True,
    "depends": [
        "arabic_project_scrum",
        "project_template_project_project",
        "project_task_code_project",
        "bsi_checklist_and_reminders_project",
        "project_stage_state_project",
        "hr_timesheet_task_domain_project",
        "hr_timesheet_task_stage_project",
        "project_hr_project",
        "project_key_project",
        "project_list_project",
        "project_mail_chatter_project",
        "project_milestone_project",
        "project_parent_task_filter_project",
        "project_recalculate_project",
        "project_role_project",
        "project_stage_closed_project",
        "project_status_project",
        "project_tag_project",
        "project_task_default_stage_project",
        "project_task_dependency_project",
        "project_task_material_project",
        "project_template_milestone_project",
        "project_timeline_project_project",
        "project_timeline_hr_timesheet_project",
        "project_timeline_task_dependency_project",
        "project_timesheet_time_control_project",
        "web_ir_actions_act_multi_project",
        "web_ir_actions_act_multi_project",
        "web_ir_actions_act_view_reload_project",
        "web_timeline_project_project",
        ],
    "sequence": -3,
}
